// EduPay V3.3 - operational CRUD layer for the current client-side prototype.
// NOTE: this improves workflow completeness, but production still requires a server-side backend/database.

function nextIdV33(list){return list.length?Math.max(...list.map(x=>Number(x.id)||0))+1:1}
function closeCrudV33(){document.getElementById('crudModalV33')?.remove()}
function openCrudV33(title,body){closeCrudV33();const el=document.createElement('div');el.id='crudModalV33';el.className='modal-backdrop';el.innerHTML=`<div class="modal crud-modal"><div class="crud-modal-head"><div><span class="page-kicker">EduPay Admin</span><h3>${title}</h3></div><button type="button" class="modal-close-v33" onclick="closeCrudV33()">×</button></div>${body}</div>`;document.body.appendChild(el)}
function activeTextV33(v){return v===false?'<span class="badge danger"><i></i>Nonaktif</span>':'<span class="badge ok"><i></i>Aktif</span>'}
function billBadgeV33(s){if(s==='paid')return '<span class="badge ok"><i></i>Lunas</span>';if(s==='pending')return '<span class="badge warn"><i></i>Menunggu Verifikasi</span>';if(s==='cancelled')return '<span class="badge info"><i></i>Dibatalkan</span>';return '<span class="badge danger"><i></i>Belum Bayar</span>'}

function studentsV33(){
  return `<div class="page-head"><div><span class="page-kicker">Master Data</span><h2>Master Siswa</h2><p>Tambah, ubah, aktifkan, atau nonaktifkan data siswa dan wali.</p></div><button class="btn btn-primary" onclick="studentFormV33()">+ Tambah Siswa</button></div>
  <div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>NIS</th><th>Nama</th><th>Kelas</th><th>Wali</th><th>No HP</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${db.students.map(s=>`<tr><td>${esc(s.nis)}</td><td><b>${esc(s.name)}</b></td><td>${esc(className(s.classId))}</td><td>${esc(s.parent)}</td><td>${esc(s.phone)}</td><td>${activeTextV33(s.active)}</td><td><div class="row-actions-v33"><button class="btn btn-soft btn-sm" onclick="studentFormV33(${s.id})">Edit</button><button class="btn ${s.active===false?'btn-ghost':'btn-danger'} btn-sm" onclick="toggleStudentV33(${s.id})">${s.active===false?'Aktifkan':'Nonaktifkan'}</button></div></td></tr>`).join('')}</tbody></table></div></div>`
}
function studentFormV33(id=null){const s=id?byId(db.students,id):null;openCrudV33(s?'Edit Siswa':'Tambah Siswa',`<form onsubmit="saveStudentV33(event,${id||'null'})"><div class="modal-grid"><div><label>NIS</label><input id="crudNis" class="field" required value="${esc(s?.nis||'')}"></div><div><label>Nama Siswa</label><input id="crudStudentName" class="field" required value="${esc(s?.name||'')}"></div><div><label>Kelas</label><select id="crudClassId" class="field" required>${db.classes.map(c=>`<option value="${c.id}" ${Number(s?.classId)===Number(c.id)?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div><label>Nama Wali</label><input id="crudParent" class="field" required value="${esc(s?.parent||'')}"></div><div class="span-2-v33"><label>No. HP Wali</label><input id="crudPhone" class="field" required value="${esc(s?.phone||'')}"></div></div><div class="modal-actions"><button type="button" class="btn btn-ghost" onclick="closeCrudV33()">Batal</button><button class="btn btn-primary">Simpan</button></div></form>`)}
function saveStudentV33(e,id){e.preventDefault();const nis=crudNis.value.trim(),name=crudStudentName.value.trim(),classId=Number(crudClassId.value),parent=crudParent.value.trim(),phone=crudPhone.value.trim();if(db.students.some(x=>x.nis===nis&&Number(x.id)!==Number(id)))return toast('NIS sudah digunakan siswa lain');if(id){Object.assign(byId(db.students,id),{nis,name,classId,parent,phone})}else{db.students.push({id:nextIdV33(db.students),nis,name,classId,parent,phone,active:true})}save();closeCrudV33();render();toast('Data siswa berhasil disimpan')}
function toggleStudentV33(id){const s=byId(db.students,id);if(!s)return;s.active=s.active===false;save();render();toast(s.active===false?'Siswa dinonaktifkan':'Siswa diaktifkan kembali')}

function feesV33(){return `<div class="page-head"><div><span class="page-kicker">Master Data</span><h2>Jenis Pembayaran</h2><p>Kelola komponen biaya, nominal, dan periode penagihan.</p></div><button class="btn btn-primary" onclick="feeFormV33()">+ Tambah Jenis</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Nama</th><th>Nominal</th><th>Periode</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${db.feeTypes.map(f=>`<tr><td><b>${esc(f.name)}</b></td><td>${rupiah(f.amount)}</td><td>${esc(f.period)}</td><td>${activeTextV33(f.active)}</td><td><div class="row-actions-v33"><button class="btn btn-soft btn-sm" onclick="feeFormV33(${f.id})">Edit</button><button class="btn ${f.active===false?'btn-ghost':'btn-danger'} btn-sm" onclick="toggleFeeV33(${f.id})">${f.active===false?'Aktifkan':'Nonaktifkan'}</button></div></td></tr>`).join('')}</tbody></table></div></div>`}
function feeFormV33(id=null){const f=id?byId(db.feeTypes,id):null;openCrudV33(f?'Edit Jenis Pembayaran':'Tambah Jenis Pembayaran',`<form onsubmit="saveFeeV33(event,${id||'null'})"><div class="modal-grid"><div class="span-2-v33"><label>Nama Pembayaran</label><input id="crudFeeName" class="field" required value="${esc(f?.name||'')}"></div><div><label>Nominal</label><input id="crudFeeAmount" class="field" type="number" min="0" required value="${Number(f?.amount||0)}"></div><div><label>Periode</label><select id="crudFeePeriod" class="field"><option ${f?.period==='Bulanan'?'selected':''}>Bulanan</option><option ${f?.period==='Tahunan'?'selected':''}>Tahunan</option><option ${f?.period==='Sekali'?'selected':''}>Sekali</option><option ${f?.period==='Semester'?'selected':''}>Semester</option></select></div></div><div class="modal-actions"><button type="button" class="btn btn-ghost" onclick="closeCrudV33()">Batal</button><button class="btn btn-primary">Simpan</button></div></form>`)}
function saveFeeV33(e,id){e.preventDefault();const name=crudFeeName.value.trim(),amount=Number(crudFeeAmount.value),period=crudFeePeriod.value;if(id){Object.assign(byId(db.feeTypes,id),{name,amount,period})}else{db.feeTypes.push({id:nextIdV33(db.feeTypes),name,amount,period,active:true})}save();closeCrudV33();render();toast('Jenis pembayaran berhasil disimpan')}
function toggleFeeV33(id){const f=byId(db.feeTypes,id);if(!f)return;f.active=f.active===false;save();render();toast(f.active===false?'Jenis pembayaran dinonaktifkan':'Jenis pembayaran diaktifkan')}

function billsV33(){const rows=db.bills.slice().sort((a,b)=>Number(b.id)-Number(a.id));return `<div class="page-head"><div><span class="page-kicker">Penagihan</span><h2>Tagihan Siswa</h2><p>Buat tagihan individual atau massal dan kelola status penagihan.</p></div><div class="head-actions-v33"><button class="btn btn-soft" onclick="massBillFormV33()">Buat Massal</button><button class="btn btn-primary" onclick="billFormV33()">+ Tambah Tagihan</button></div></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Siswa</th><th>Tagihan</th><th>Jatuh Tempo</th><th>Nominal</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${rows.map(b=>`<tr><td>${esc(studentName(b.studentId))}</td><td><b>${esc(b.title)}</b></td><td>${esc(b.due)}</td><td>${rupiah(b.amount)}</td><td>${billBadgeV33(b.status)}</td><td><div class="row-actions-v33">${b.status!=='paid'&&b.status!=='cancelled'?`<button class="btn btn-soft btn-sm" onclick="billFormV33(${b.id})">Edit</button><button class="btn btn-danger btn-sm" onclick="cancelBillV33(${b.id})">Batalkan</button>`:b.status==='cancelled'?`<button class="btn btn-ghost btn-sm" onclick="restoreBillV33(${b.id})">Pulihkan</button>`:'<span class="locked-v33">Terkunci setelah lunas</span>'}</div></td></tr>`).join('')}</tbody></table></div></div>`}
function billFormV33(id=null){const b=id?byId(db.bills,id):null;const students=db.students.filter(s=>s.active!==false);openCrudV33(b?'Edit Tagihan':'Tambah Tagihan',`<form onsubmit="saveBillV33(event,${id||'null'})"><div class="modal-grid"><div class="span-2-v33"><label>Siswa</label><select id="crudBillStudent" class="field" required>${students.map(s=>`<option value="${s.id}" ${Number(b?.studentId)===Number(s.id)?'selected':''}>${esc(s.name)} — ${esc(className(s.classId))}</option>`).join('')}</select></div><div class="span-2-v33"><label>Nama Tagihan</label><input id="crudBillTitle" class="field" required value="${esc(b?.title||'')}"></div><div><label>Nominal</label><input id="crudBillAmount" class="field" type="number" min="0" required value="${Number(b?.amount||0)}"></div><div><label>Jatuh Tempo</label><input id="crudBillDue" class="field" type="date" required value="${esc(b?.due||'')}"></div></div><div class="modal-actions"><button type="button" class="btn btn-ghost" onclick="closeCrudV33()">Batal</button><button class="btn btn-primary">Simpan</button></div></form>`)}
function saveBillV33(e,id){e.preventDefault();const studentId=Number(crudBillStudent.value),title=crudBillTitle.value.trim(),amount=Number(crudBillAmount.value),due=crudBillDue.value;if(id){const b=byId(db.bills,id);if(b.status==='paid')return toast('Tagihan lunas tidak dapat diubah');Object.assign(b,{studentId,title,amount,due})}else{db.bills.push({id:nextIdV33(db.bills),studentId,title,amount,due,status:'unpaid'})}save();closeCrudV33();render();toast('Tagihan berhasil disimpan')}
function cancelBillV33(id){const b=byId(db.bills,id);if(!b||b.status==='paid')return;if(!confirm('Batalkan tagihan ini?'))return;b.status='cancelled';save();render();toast('Tagihan dibatalkan')}
function restoreBillV33(id){const b=byId(db.bills,id);if(!b)return;b.status='unpaid';save();render();toast('Tagihan dipulihkan')}
function massBillFormV33(){const fees=db.feeTypes.filter(f=>f.active!==false);openCrudV33('Buat Tagihan Massal',`<form onsubmit="createMassBillV33(event)"><div class="modal-grid"><div><label>Jenis Pembayaran</label><select id="massFeeId" class="field" required onchange="syncMassFeeV33()">${fees.map(f=>`<option value="${f.id}">${esc(f.name)} — ${rupiah(f.amount)}</option>`).join('')}</select></div><div><label>Kelas</label><select id="massClassId" class="field"><option value="all">Semua Kelas</option>${db.classes.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="span-2-v33"><label>Judul Tagihan</label><input id="massTitle" class="field" required value="${esc(fees[0]?.name||'')}"></div><div><label>Nominal</label><input id="massAmount" class="field" type="number" min="0" required value="${Number(fees[0]?.amount||0)}"></div><div><label>Jatuh Tempo</label><input id="massDue" class="field" type="date" required></div></div><div class="proof-note">Sistem melewati siswa yang sudah memiliki judul tagihan yang sama agar tidak terjadi duplikasi.</div><div class="modal-actions"><button type="button" class="btn btn-ghost" onclick="closeCrudV33()">Batal</button><button class="btn btn-primary">Buat Tagihan</button></div></form>`)}
function syncMassFeeV33(){const f=byId(db.feeTypes,massFeeId.value);if(!f)return;massTitle.value=f.name;massAmount.value=f.amount}
function createMassBillV33(e){e.preventDefault();const cls=massClassId.value,title=massTitle.value.trim(),amount=Number(massAmount.value),due=massDue.value;let students=db.students.filter(s=>s.active!==false&&(cls==='all'||Number(s.classId)===Number(cls))),created=0;students.forEach(s=>{if(db.bills.some(b=>Number(b.studentId)===Number(s.id)&&b.title===title&&b.status!=='cancelled'))return;db.bills.push({id:nextIdV33(db.bills),studentId:s.id,title,amount,due,status:'unpaid'});created++});save();closeCrudV33();render();toast(`${created} tagihan berhasil dibuat`)}

function paymentsV33(){const openBills=db.bills.filter(b=>!['paid','cancelled'].includes(b.status));const livePayments=db.payments.slice().reverse();return `<div class="page-head"><div><span class="page-kicker">Kas & Penerimaan</span><h2>Pembayaran</h2><p>Catat pembayaran dan lakukan pembatalan transaksi jika terjadi salah input.</p></div></div><div class="toolbar"><select id="payBill" class="field">${openBills.map(b=>`<option value="${b.id}">${esc(studentName(b.studentId))} — ${esc(b.title)}</option>`).join('')}</select><select id="payMethod" class="field"><option>Cash</option><option>Transfer</option><option>QRIS</option></select><button class="btn btn-primary" onclick="paySelected()" ${openBills.length?'':'disabled'}>Catat Pembayaran</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Kwitansi</th><th>Tanggal</th><th>Siswa</th><th>Nominal</th><th>Metode</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${livePayments.map(p=>`<tr><td><b>${esc(p.receipt)}</b></td><td>${esc(p.date)}</td><td>${esc(studentName(p.studentId))}</td><td>${rupiah(p.amount)}</td><td>${esc(p.method)}</td><td>${p.voided?'<span class="badge danger"><i></i>Dibatalkan</span>':'<span class="badge ok"><i></i>Valid</span>'}</td><td>${p.voided?'<span class="locked-v33">Void</span>':`<button class="btn btn-danger btn-sm" onclick="voidPaymentV33(${p.id})">Batalkan</button>`}</td></tr>`).join('')}</tbody></table></div></div>`}
function voidPaymentV33(id){const p=db.payments.find(x=>Number(x.id)===Number(id));if(!p||p.voided)return;if(!confirm('Batalkan transaksi pembayaran ini? Nomor kwitansi tetap disimpan sebagai jejak audit.'))return;p.voided=true;p.voidedAt=new Date().toISOString();const b=byId(db.bills,p.billId);if(b)b.status='unpaid';save();render();toast('Transaksi dibatalkan dan tagihan dibuka kembali')}

function reportsV33(){const validPayments=db.payments.filter(p=>!p.voided),paid=validPayments.reduce((s,p)=>s+Number(p.amount||0),0),unpaid=db.bills.filter(b=>['unpaid','pending'].includes(b.status)).reduce((s,b)=>s+Number(b.amount||0),0),pending=db.bills.filter(b=>b.status==='pending').length;return `<div class="page-head"><div><span class="page-kicker">Pelaporan</span><h2>Laporan</h2><p>Ringkasan penerimaan, tunggakan, dan pembayaran yang perlu diverifikasi.</p></div><button class="btn btn-soft" onclick="exportCSV()">Export CSV</button></div><div class="grid stats">${stat('Penerimaan',rupiah(paid),'stat-green')}${stat('Tunggakan',rupiah(unpaid),'stat-red')}${stat('Menunggu Verifikasi',pending,'stat-amber')}</div><div class="card">${billTable(db.bills.filter(b=>['unpaid','pending'].includes(b.status)))}</div>`}
function historyV33(){const rows=db.payments.filter(p=>Number(p.studentId)===Number(session.studentId)&&!p.voided).slice().reverse();return `<div class="page-head"><div><h2>Riwayat Pembayaran</h2><p>Pembayaran yang telah diverifikasi.</p></div></div><div class="card">${paymentsTable(rows)}</div>`}

function dashboardV33(){if(session.role==='parent'){let list=db.bills.filter(b=>Number(b.studentId)===Number(session.studentId)&&b.status!=='cancelled'),s=byId(db.students,session.studentId);return `<div class="page-head"><div><span class="page-kicker">Portal Orang Tua</span><h2>Halo, ${esc(session.name.split(' ')[0])} 👋</h2><p>${esc(s?.name)} · ${esc(className(s?.classId))}</p></div></div><div class="welcome-card"><div class="welcome-icon">✓</div><div><b>Pembayaran sekolah dalam satu tampilan</b><p>Lihat tagihan, kirim bukti transfer, dan simpan kwitansi pembayaran.</p></div></div><div class="grid stats">${stat('Belum Bayar',rupiah(list.filter(b=>b.status==='unpaid').reduce((a,b)=>a+b.amount,0)),'stat-red','mybills','unpaid')}${stat('Sudah Dibayar',rupiah(list.filter(b=>b.status==='paid').reduce((a,b)=>a+b.amount,0)),'stat-green','history')}${stat('Jumlah Tagihan',list.length,'stat-blue','mybills','all')}${stat('Menunggu Verifikasi',list.filter(b=>b.status==='pending').length,'stat-amber','mybills','pending')}</div><div class="card">${billTable(list.filter(b=>!['paid','cancelled'].includes(b.status)),true)}</div>`}
  const bills=db.bills.filter(b=>b.status!=='cancelled'),validPayments=db.payments.filter(p=>!p.voided),total=bills.reduce((s,b)=>s+b.amount,0),paid=validPayments.reduce((s,p)=>s+p.amount,0),unpaid=bills.filter(b=>b.status==='unpaid').reduce((s,b)=>s+b.amount,0),pending=bills.filter(b=>b.status==='pending').length;return `<div class="page-head"><div><span class="page-kicker">Ringkasan hari ini</span><h2>Halo, ${esc(session.name.split(' ')[0])} 👋</h2><p>Pantau pembayaran siswa dan pekerjaan yang perlu ditindaklanjuti.</p></div></div><div class="grid stats">${stat('Total Tagihan',rupiah(total),'stat-blue',session.role==='finance'?'payments':'bills','all')}${stat('Sudah Dibayar',rupiah(paid),'stat-green','reports','paid')}${stat('Belum Dibayar',rupiah(unpaid),'stat-red',session.role==='finance'?'payments':'bills','unpaid')}${stat('Perlu Verifikasi',pending,'stat-amber',session.role==='finance'?'verification':'bills','pending')}</div><div class="card table-card"><div class="section-head"><div><h3>Transaksi Terbaru</h3><p>5 pembayaran valid terakhir.</p></div></div>${paymentsTable(validPayments.slice().reverse().slice(0,5))}</div>`}

// Critical router repair: app.js created `views` before later overrides existed.
// Rebind the live router to the newest implementations so readonly legacy pages are no longer used.
Object.assign(views,{
  dashboard:dashboardV33,
  students:studentsV33,
  fees:feesV33,
  bills:billsV33,
  payments:paymentsV33,
  verification:verification,
  reports:reportsV33,
  mybills:mybills,
  history:historyV33
});
render();
