const STORAGE='edupay-simple-v1',SESSION='edupay-session';
const rupiah=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
const seed={users:[{id:1,name:'Administrator',username:'admin',password:'admin123',role:'admin'},{id:2,name:'Bendahara Sekolah',username:'finance',password:'finance123',role:'finance'},{id:3,name:'Budi Santoso',username:'081234567890',password:'wali123',role:'parent',studentId:1}],classes:[{id:1,name:'X RPL 1'},{id:2,name:'XI DKV 1'}],students:[{id:1,nis:'24001',name:'Andi Santoso',classId:1,parent:'Budi Santoso',phone:'081234567890'},{id:2,nis:'24002',name:'Siti Aulia',classId:1,parent:'Rina Aulia',phone:'081298765432'},{id:3,nis:'23011',name:'Raka Pratama',classId:2,parent:'Deni Pratama',phone:'081377788899'}],feeTypes:[{id:1,name:'SPP Bulanan',amount:350000,period:'Bulanan'},{id:2,name:'Uang Kegiatan',amount:500000,period:'Tahunan'}],bills:[{id:1,studentId:1,title:'SPP Agustus 2026',amount:350000,due:'2026-08-10',status:'unpaid'},{id:2,studentId:1,title:'Uang Kegiatan 2026/2027',amount:500000,due:'2026-08-31',status:'pending',proofName:'bukti-transfer.jpg'},{id:3,studentId:2,title:'SPP Agustus 2026',amount:350000,due:'2026-08-10',status:'paid'},{id:4,studentId:3,title:'SPP Agustus 2026',amount:350000,due:'2026-08-10',status:'unpaid'}],payments:[{id:1,billId:3,studentId:2,amount:350000,method:'Cash',date:'2026-08-08',verifiedBy:'Bendahara Sekolah',receipt:'PAY-20260808-0001'}]};
let db=JSON.parse(localStorage.getItem(STORAGE)||'null')||structuredClone(seed),session=JSON.parse(localStorage.getItem(SESSION)||'null'),page='dashboard';
const save=()=>localStorage.setItem(STORAGE,JSON.stringify(db));const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const byId=(a,id)=>a.find(x=>x.id===Number(id));const studentName=id=>byId(db.students,id)?.name||'-';const className=id=>byId(db.classes,id)?.name||'-';
function toast(t){let d=document.createElement('div');d.className='toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
function badge(s){return s==='paid'?'<span class="badge ok"><i></i>Lunas</span>':s==='pending'?'<span class="badge warn"><i></i>Menunggu Verifikasi</span>':'<span class="badge danger"><i></i>Belum Bayar</span>'}
function role(){return session.role==='admin'?'Administrator':session.role==='finance'?'Finance / Bendahara':'Orang Tua / Wali'}
function nav(){return session.role==='admin'?[['dashboard','Dashboard'],['students','Data Siswa'],['fees','Jenis Pembayaran'],['bills','Tagihan'],['reports','Laporan']]:session.role==='finance'?[['dashboard','Dashboard'],['payments','Pembayaran'],['verification','Verifikasi Bukti'],['reports','Laporan']]:[['dashboard','Beranda'],['mybills','Tagihan Saya'],['history','Riwayat'],['profile','Profil']]}
function loginView(){return `<div class="login-wrap"><div class="login-shell"><section class="login-visual"><div class="visual-badge">Pembayaran sekolah jadi lebih mudah</div><div class="visual-copy"><div class="brand"><div class="logo-mark logo-mark-light">E</div><div><h1>EduPay</h1><small>School Finance</small></div></div><h2>Kelola pembayaran sekolah dengan lebih rapi, cepat, dan transparan.</h2><p>Satu tempat untuk tagihan siswa, verifikasi pembayaran, riwayat transaksi, dan laporan keuangan sekolah.</p><div class="feature-list"><div>✓ Status tagihan mudah dipantau</div><div>✓ Verifikasi pembayaran lebih praktis</div><div>✓ Kwitansi digital siap dicetak</div></div></div><div class="visual-footer">Simple · Mobile friendly · Siap dikembangkan</div></section><section class="login-panel"><div class="mobile-brand"><div class="logo-mark">E</div><div><strong>EduPay</strong><span>School Finance</span></div></div><div class="login-heading"><span>Selamat datang kembali</span><h3>Masuk ke akun Anda</h3><p>Gunakan akun yang diberikan oleh sekolah.</p></div><form onsubmit="login(event)"><label>Username / No. HP</label><div class="input-wrap"><span class="input-symbol">@</span><input id="username" class="field field-icon" required placeholder="admin atau 08xxxxxxxxxx"></div><label>Password</label><div class="input-wrap"><span class="input-symbol">•</span><input id="password" class="field field-icon" type="password" required placeholder="Masukkan password"></div><button class="btn btn-primary w-full login-button">Masuk ke EduPay <span>→</span></button></form><div class="demo-card"><div class="demo-title"><span>Mode Demo</span><small>Pilih akun untuk mencoba</small></div><div class="demo-grid"><button onclick="fillDemo('admin','admin123')"><b>Admin</b><span>admin</span></button><button onclick="fillDemo('finance','finance123')"><b>Finance</b><span>finance</span></button><button onclick="fillDemo('081234567890','wali123')"><b>Wali</b><span>0812…</span></button></div></div></section></div></div>`}
function fillDemo(u,p){username.value=u;password.value=p}function login(e){e.preventDefault();let u=username.value.trim(),p=password.value,f=db.users.find(x=>x.username===u&&x.password===p);if(!f)return toast('Username atau password salah');session=f;localStorage.setItem(SESSION,JSON.stringify(f));render()}function logout(){session=null;localStorage.removeItem(SESSION);page='dashboard';render()}function go(p){page=p;render()}
function shell(content){let items=nav(),pending=db.bills.filter(x=>x.status==='pending').length;return `<div class="app-shell"><aside class="sidebar"><div class="sidebar-brand"><div class="logo-mark">E</div><div><strong>EduPay</strong><span>School Finance</span></div></div><div class="nav-title">Menu Utama</div><div class="nav-list">${items.map(([p,l])=>`<button class="nav-btn ${page===p?'active':''}" onclick="go('${p}')"><span>▣</span><span>${l}</span>${p==='verification'&&pending?`<em>${pending}</em>`:''}</button>`).join('')}</div><div class="sidebar-help"><div class="help-icon">?</div><div><b>Butuh bantuan?</b><small>Hubungi admin sekolah jika ada kendala pembayaran.</small></div></div><button class="sidebar-user" onclick="logout()"><div class="avatar">${esc(session.name[0])}</div><div><b>${esc(session.name)}</b><span>${role()}</span></div><span>↪</span></button></aside><div class="content-shell"><header class="topbar"><div><div class="eyebrow">EduPay · ${role()}</div><div class="top-title">${items.find(x=>x[0]===page)?.[1]||'Dashboard'}</div></div><div class="top-actions"><button class="icon-btn">🔔${pending?'<span class="notification-dot"></span>':''}</button><div class="top-user"><div class="avatar">${esc(session.name[0])}</div><div class="name"><b>${esc(session.name)}</b><span>${role()}</span></div></div></div></header><main class="main">${content}</main></div><nav class="mobile-nav">${items.slice(0,4).map(([p,l])=>`<button class="${page===p?'active':''}" onclick="go('${p}')"><span>▣</span><span>${l}</span></button>`).join('')}</nav></div>`}
function billTable(list,parent=false){if(!list.length)return '<div class="empty">Belum ada data tagihan.</div>';return `<div class="table-wrap"><table class="table"><thead><tr>${parent?'':'<th>Siswa</th>'}<th>Tagihan</th><th>Jatuh Tempo</th><th>Nominal</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${list.map(b=>`<tr>${parent?'':`<td>${studentName(b.studentId)}</td>`}<td><b>${esc(b.title)}</b></td><td>${b.due}</td><td>${rupiah(b.amount)}</td><td>${badge(b.status)}</td><td>${parent?(b.status==='unpaid'?`<button class="btn btn-soft btn-sm" onclick="uploadProof(${b.id})">Upload Bukti</button>`:b.status==='paid'?`<button class="btn btn-ghost btn-sm" onclick="receipt(${b.id})">Kwitansi</button>`:'Menunggu'):`<button class="btn btn-soft btn-sm" onclick="pay(${b.id},'Cash')">Catat Bayar</button>`}</td></tr>`).join('')}</tbody></table></div>`}
function paymentsTable(list){if(!list.length)return '<div class="empty">Belum ada transaksi.</div>';return `<div class="table-wrap"><table class="table"><thead><tr><th>Kwitansi</th><th>Tanggal</th><th>Siswa</th><th>Nominal</th><th>Metode</th></tr></thead><tbody>${list.map(p=>`<tr><td><b>${p.receipt}</b></td><td>${p.date}</td><td>${studentName(p.studentId)}</td><td>${rupiah(p.amount)}</td><td>${p.method}</td></tr>`).join('')}</tbody></table></div>`}
function dashboard(){if(session.role==='parent')return parentDashboard();let total=db.bills.reduce((s,b)=>s+b.amount,0),paid=db.bills.filter(b=>b.status==='paid').reduce((s,b)=>s+b.amount,0),unpaid=db.bills.filter(b=>b.status==='unpaid').reduce((s,b)=>s+b.amount,0),pending=db.bills.filter(b=>b.status==='pending').length;return `<div class="page-head"><div><span class="page-kicker">Ringkasan hari ini</span><h2>Halo, ${esc(session.name.split(' ')[0])} 👋</h2><p>Pantau pembayaran siswa dan pekerjaan yang perlu ditindaklanjuti.</p></div></div><div class="grid stats">${stat('Total Tagihan',rupiah(total),'stat-blue')}${stat('Sudah Dibayar',rupiah(paid),'stat-green')}${stat('Belum Dibayar',rupiah(unpaid),'stat-red')}${stat('Perlu Verifikasi',pending,'stat-amber')}</div><div class="card table-card"><div class="section-head"><div><h3>Transaksi Terbaru</h3><p>5 pembayaran terakhir.</p></div></div>${paymentsTable(db.payments.slice().reverse().slice(0,5))}</div>`}
function stat(t,v,c){return `<div class="card stat-card ${c}"><div class="stat-top"><div class="stat-icon">●</div><span>${t}</span></div><div class="stat-value">${v}</div><div class="stat-sub">Data EduPay saat ini</div></div>`}
function parentDashboard(){let list=db.bills.filter(b=>b.studentId===session.studentId),s=byId(db.students,session.studentId);return `<div class="page-head"><div><span class="page-kicker">Portal Orang Tua</span><h2>Halo, ${esc(session.name.split(' ')[0])} 👋</h2><p>${esc(s?.name)} · ${className(s?.classId)}</p></div></div><div class="welcome-card"><div class="welcome-icon">✓</div><div><b>Pembayaran sekolah dalam satu tampilan</b><p>Lihat tagihan, kirim bukti transfer, dan simpan kwitansi pembayaran.</p></div></div><div class="grid stats">${stat('Belum Bayar',rupiah(list.filter(b=>b.status==='unpaid').reduce((a,b)=>a+b.amount,0)),'stat-red')}${stat('Sudah Dibayar',rupiah(list.filter(b=>b.status==='paid').reduce((a,b)=>a+b.amount,0)),'stat-green')}${stat('Jumlah Tagihan',list.length,'stat-blue')}${stat('Menunggu Verifikasi',list.filter(b=>b.status==='pending').length,'stat-amber')}</div><div class="card">${billTable(list.filter(b=>b.status!=='paid'),true)}</div>`}
function students(){return `<div class="page-head"><div><h2>Master Siswa</h2><p>Kelola data siswa dan wali.</p></div></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>NIS</th><th>Nama</th><th>Kelas</th><th>Wali</th><th>No HP</th></tr></thead><tbody>${db.students.map(s=>`<tr><td>${s.nis}</td><td><b>${s.name}</b></td><td>${className(s.classId)}</td><td>${s.parent}</td><td>${s.phone}</td></tr>`).join('')}</tbody></table></div></div>`}
function fees(){return `<div class="page-head"><div><h2>Jenis Pembayaran</h2><p>Komponen biaya sekolah.</p></div></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Nama</th><th>Nominal</th><th>Periode</th></tr></thead><tbody>${db.feeTypes.map(f=>`<tr><td><b>${f.name}</b></td><td>${rupiah(f.amount)}</td><td>${f.period}</td></tr>`).join('')}</tbody></table></div></div>`}
function bills(){return `<div class="page-head"><div><h2>Tagihan Siswa</h2><p>Pantau seluruh tagihan siswa.</p></div></div><div class="card">${billTable(db.bills)}</div>`}
function payments(){return `<div class="page-head"><div><h2>Pembayaran</h2><p>Catat transaksi pembayaran sekolah.</p></div></div><div class="toolbar"><select id="payBill" class="field">${db.bills.filter(b=>b.status!=='paid').map(b=>`<option value="${b.id}">${studentName(b.studentId)} — ${b.title}</option>`).join('')}</select><select id="payMethod" class="field"><option>Cash</option><option>Transfer</option><option>QRIS</option></select><button class="btn btn-primary" onclick="paySelected()">Catat Pembayaran</button></div><div class="card">${paymentsTable(db.payments.slice().reverse())}</div>`}
function paySelected(){let b=byId(db.bills,payBill.value);if(b)pay(b.id,payMethod.value)}function pay(id,method){let b=byId(db.bills,id);if(!b||b.status==='paid')return;b.status='paid';let date=new Date().toISOString().slice(0,10),receipt='PAY-'+date.replaceAll('-','')+'-'+String(db.payments.length+1).padStart(4,'0');db.payments.push({id:Date.now(),billId:b.id,studentId:b.studentId,amount:b.amount,method,date,verifiedBy:session.name,receipt});save();render();toast('Pembayaran berhasil dicatat')}
function verification(){let list=db.bills.filter(b=>b.status==='pending');return `<div class="page-head"><div><h2>Verifikasi Bukti</h2><p>Konfirmasi bukti transfer dari wali.</p></div></div><div class="card">${list.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Siswa</th><th>Tagihan</th><th>Bukti</th><th>Nominal</th><th>Aksi</th></tr></thead><tbody>${list.map(b=>`<tr><td>${studentName(b.studentId)}</td><td>${b.title}</td><td>${b.proofName||'-'}</td><td>${rupiah(b.amount)}</td><td><button class="btn btn-primary btn-sm" onclick="pay(${b.id},'Transfer')">Terima</button> <button class="btn btn-danger btn-sm" onclick="reject(${b.id})">Tolak</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Tidak ada bukti yang menunggu verifikasi.</div>'}</div>`}function reject(id){let b=byId(db.bills,id);b.status='unpaid';delete b.proofName;save();render();toast('Bukti ditolak')}
function reports(){let paid=db.payments.reduce((s,p)=>s+p.amount,0),unpaid=db.bills.filter(b=>b.status!=='paid').reduce((s,b)=>s+b.amount,0);return `<div class="page-head"><div><h2>Laporan</h2><p>Ringkasan penerimaan dan tunggakan.</p></div><button class="btn btn-soft" onclick="exportCSV()">Export CSV</button></div><div class="grid stats">${stat('Penerimaan',rupiah(paid),'stat-green')}${stat('Tunggakan',rupiah(unpaid),'stat-red')}</div><div class="card">${billTable(db.bills.filter(b=>b.status!=='paid'))}</div>`}
function exportCSV(){let rows=[['NIS','Nama','Kelas','Tagihan','Nominal','Jatuh Tempo','Status']];db.bills.forEach(b=>{let s=byId(db.students,b.studentId);rows.push([s?.nis,s?.name,className(s?.classId),b.title,b.amount,b.due,b.status])});let blob=new Blob([rows.map(r=>r.join(',')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='laporan-edupay.csv';a.click()}
function mybills(){return `<div class="page-head"><div><h2>Tagihan Saya</h2><p>Daftar kewajiban pembayaran siswa.</p></div></div><div class="card">${billTable(db.bills.filter(b=>b.studentId===session.studentId),true)}</div>`}
function history(){return `<div class="page-head"><div><h2>Riwayat Pembayaran</h2><p>Pembayaran yang telah diverifikasi.</p></div></div><div class="card">${paymentsTable(db.payments.filter(p=>p.studentId===session.studentId).slice().reverse())}</div>`}
function profile(){let s=byId(db.students,session.studentId);return `<div class="page-head"><div><h2>Profil Wali</h2><p>Data siswa yang terhubung.</p></div></div><div class="card" style="max-width:600px"><div class="receipt-row"><span>Nama Wali</span><b>${session.name}</b></div><div class="receipt-row"><span>Nama Siswa</span><b>${s?.name||'-'}</b></div><div class="receipt-row"><span>NIS</span><b>${s?.nis||'-'}</b></div><div class="receipt-row"><span>Kelas</span><b>${className(s?.classId)}</b></div><div class="receipt-row"><span>No HP</span><b>${s?.phone||'-'}</b></div></div>`}
function uploadProof(id){let name=prompt('Nama file bukti pembayaran (demo):','bukti-transfer.jpg');if(!name)return;let b=byId(db.bills,id);b.status='pending';b.proofName=name;save();render();toast('Bukti dikirim ke bendahara')}
function receipt(id){let p=db.payments.find(x=>x.billId===id),b=byId(db.bills,id),s=byId(db.students,b?.studentId);if(!p)return toast('Kwitansi belum tersedia');let w=window.open('','_blank');w.document.write(`<html><body style="font-family:Arial;padding:40px"><h2>KWITANSI PEMBAYARAN</h2><p>No: ${p.receipt}</p><p>Siswa: ${s.name}</p><p>Pembayaran: ${b.title}</p><h3>${rupiah(p.amount)}</h3><p>Status: LUNAS</p><button onclick="print()">Cetak</button></body></html>`)}
const views={dashboard,students,fees,bills,payments,verification,reports,mybills,history,profile};function render(){document.getElementById('app').innerHTML=session?shell((views[page]||dashboard)()):loginView()}render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
