var edupayBillFilter='all';
const edupayLogo='<img src="assets/edupay-logo.svg" class="brand-logo" alt="Logo EduPay">';

function go(p,filter=null){page=p;if(filter!==null)edupayBillFilter=filter;render()}

function shell(content){let items=nav(),pending=db.bills.filter(x=>x.status==='pending').length;return `<div class="app-shell"><aside class="sidebar"><div class="sidebar-brand">${edupayLogo}<div><strong>EduPay</strong><span>School Finance</span></div></div><div class="nav-title">Menu Utama</div><div class="nav-list">${items.map(([p,l])=>`<button class="nav-btn ${page===p?'active':''}" onclick="go('${p}')"><span>▣</span><span>${l}</span>${p==='verification'&&pending?`<em>${pending}</em>`:''}</button>`).join('')}</div><div class="sidebar-help"><div class="help-icon">?</div><div><b>Butuh bantuan?</b><small>Hubungi admin sekolah jika ada kendala pembayaran.</small></div></div><button class="sidebar-user" onclick="logout()"><div class="avatar">${esc(session.name[0])}</div><div><b>${esc(session.name)}</b><span>${role()}</span></div><span>↪</span></button></aside><div class="content-shell"><header class="topbar"><div><div class="eyebrow">EduPay · ${role()}</div><div class="top-title">${items.find(x=>x[0]===page)?.[1]||'Dashboard'}</div></div><div class="top-actions"><button class="icon-btn">🔔${pending?'<span class="notification-dot"></span>':''}</button><div class="top-user"><div class="avatar">${esc(session.name[0])}</div><div class="name"><b>${esc(session.name)}</b><span>${role()}</span></div></div></div></header><main class="main">${content}</main></div><nav class="mobile-nav">${items.slice(0,4).map(([p,l])=>`<button class="${page===p?'active':''}" onclick="go('${p}')"><span>▣</span><span>${l}</span></button>`).join('')}</nav></div>`}

function stat(t,v,c,target=null,filter=null){let click=target?`onclick="go('${target}'${filter!==null?`, '${filter}'`:''})" tabindex="0" role="button"`:'';return `<div class="card stat-card ${c} ${target?'clickable':''}" ${click}><div class="stat-top"><div class="stat-icon">●</div><span>${t}</span></div><div class="stat-value">${v}</div><div class="stat-sub">Data EduPay saat ini</div>${target?'<div class="stat-link">Lihat detail →</div>':''}</div>`}

function dashboard(){if(session.role==='parent')return parentDashboard();let total=db.bills.reduce((s,b)=>s+b.amount,0),paid=db.bills.filter(b=>b.status==='paid').reduce((s,b)=>s+b.amount,0),unpaid=db.bills.filter(b=>b.status==='unpaid').reduce((s,b)=>s+b.amount,0),pending=db.bills.filter(b=>b.status==='pending').length;return `<div class="page-head"><div><span class="page-kicker">Ringkasan hari ini</span><h2>Halo, ${esc(session.name.split(' ')[0])} 👋</h2><p>Pantau pembayaran siswa dan pekerjaan yang perlu ditindaklanjuti.</p></div></div><div class="grid stats">${stat('Total Tagihan',rupiah(total),'stat-blue','bills','all')}${stat('Sudah Dibayar',rupiah(paid),'stat-green','reports','paid')}${stat('Belum Dibayar',rupiah(unpaid),'stat-red','bills','unpaid')}${stat('Perlu Verifikasi',pending,'stat-amber',session.role==='finance'?'verification':'bills','pending')}</div><div class="card table-card"><div class="section-head"><div><h3>Transaksi Terbaru</h3><p>5 pembayaran terakhir.</p></div></div>${paymentsTable(db.payments.slice().reverse().slice(0,5))}</div>`}

function parentDashboard(){let list=db.bills.filter(b=>b.studentId===session.studentId),s=byId(db.students,session.studentId);return `<div class="page-head"><div><span class="page-kicker">Portal Orang Tua</span><h2>Halo, ${esc(session.name.split(' ')[0])} 👋</h2><p>${esc(s?.name)} · ${className(s?.classId)}</p></div></div><div class="welcome-card"><div class="welcome-icon">✓</div><div><b>Pembayaran sekolah dalam satu tampilan</b><p>Lihat tagihan, kirim bukti transfer, dan simpan kwitansi pembayaran.</p></div></div><div class="grid stats">${stat('Belum Bayar',rupiah(list.filter(b=>b.status==='unpaid').reduce((a,b)=>a+b.amount,0)),'stat-red','mybills','unpaid')}${stat('Sudah Dibayar',rupiah(list.filter(b=>b.status==='paid').reduce((a,b)=>a+b.amount,0)),'stat-green','history')}${stat('Jumlah Tagihan',list.length,'stat-blue','mybills','all')}${stat('Menunggu Verifikasi',list.filter(b=>b.status==='pending').length,'stat-amber','mybills','pending')}</div><div class="card">${billTable(list.filter(b=>b.status!=='paid'),true)}</div>`}

function parentBillActions(b){if(b.status==='paid')return `<button class="btn btn-ghost btn-sm" onclick="receipt(${b.id})">Kwitansi</button>`;if(b.status==='pending')return `<span class="badge warn"><i></i>Menunggu Verifikasi</span>`;return `<button class="btn transfer-btn btn-sm" onclick="openTransferUpload(${b.id})">Transfer & Upload Bukti</button>`}

function billTable(list,parent=false){if(!list.length)return '<div class="empty">Belum ada data tagihan.</div>';return `<div class="table-wrap"><table class="table"><thead><tr>${parent?'':'<th>Siswa</th>'}<th>Tagihan</th><th>Jatuh Tempo</th><th>Nominal</th><th>Status</th><th>Aksi</th></tr></thead><tbody>${list.map(b=>`<tr>${parent?'':`<td>${studentName(b.studentId)}</td>`}<td><b>${esc(b.title)}</b></td><td>${b.due}</td><td>${rupiah(b.amount)}</td><td>${badge(b.status)}</td><td>${parent?parentBillActions(b):`<button class="btn btn-soft btn-sm" onclick="pay(${b.id},'Cash')">Catat Bayar</button>`}</td></tr>`).join('')}</tbody></table></div>`}

function mybills(){let all=db.bills.filter(b=>b.studentId===session.studentId),list=all;if(edupayBillFilter==='unpaid')list=all.filter(b=>b.status==='unpaid');if(edupayBillFilter==='pending')list=all.filter(b=>b.status==='pending');if(edupayBillFilter==='paid')list=all.filter(b=>b.status==='paid');return `<div class="page-head"><div><h2>Tagihan Saya</h2><p>Upload bukti hanya digunakan untuk pembayaran via transfer.</p></div></div><div class="filter-bar"><button class="filter-chip ${edupayBillFilter==='all'?'active':''}" onclick="edupayBillFilter='all';render()">Semua</button><button class="filter-chip ${edupayBillFilter==='unpaid'?'active':''}" onclick="edupayBillFilter='unpaid';render()">Belum Bayar</button><button class="filter-chip ${edupayBillFilter==='pending'?'active':''}" onclick="edupayBillFilter='pending';render()">Menunggu Verifikasi</button><button class="filter-chip ${edupayBillFilter==='paid'?'active':''}" onclick="edupayBillFilter='paid';render()">Lunas</button></div><div class="card">${billTable(list,true)}</div>`}

function openTransferUpload(id){let b=byId(db.bills,id);if(!b)return;let old=document.getElementById('transferProofModal');if(old)old.remove();let wrap=document.createElement('div');wrap.id='transferProofModal';wrap.className='modal-backdrop';wrap.innerHTML=`<div class="modal"><h3>Upload Bukti Transfer</h3><p style="color:#718096;margin:0">Pembayaran: <b>${esc(b.title)}</b> · ${rupiah(b.amount)}</p><div class="upload-box"><b style="display:block;color:#334155">Pilih bukti transfer</b><small style="color:#718096">JPG, PNG, atau PDF.</small><input id="transferProofFile" type="file" accept="image/jpeg,image/png,application/pdf"></div><div class="proof-note">Setelah dikirim, status akan berubah menjadi <b>Menunggu Verifikasi</b>.</div><div class="modal-actions"><button class="btn btn-ghost" onclick="document.getElementById('transferProofModal').remove()">Batal</button><button class="btn btn-primary" onclick="submitTransferProof(${b.id})">Kirim Bukti</button></div></div>`;document.body.appendChild(wrap)}

function submitTransferProof(id){let f=document.getElementById('transferProofFile')?.files?.[0];if(!f)return toast('Pilih file bukti transfer terlebih dahulu');let b=byId(db.bills,id);b.status='pending';b.paymentMethod='Transfer';b.proofName=f.name;b.proofUploadedAt=new Date().toISOString();save();document.getElementById('transferProofModal')?.remove();render();toast('Bukti transfer berhasil dikirim')}
function uploadProof(id){openTransferUpload(id)}

function verification(){let list=db.bills.filter(b=>b.status==='pending');return `<div class="page-head"><div><h2>Verifikasi Bukti</h2><p>Konfirmasi bukti transfer dari wali.</p></div></div><div class="card">${list.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Siswa</th><th>Tagihan</th><th>Metode</th><th>Bukti</th><th>Nominal</th><th>Aksi</th></tr></thead><tbody>${list.map(b=>`<tr><td>${studentName(b.studentId)}</td><td>${b.title}</td><td>${b.paymentMethod||'Transfer'}</td><td>${esc(b.proofName||'-')}</td><td>${rupiah(b.amount)}</td><td><button class="btn btn-primary btn-sm" onclick="pay(${b.id},'Transfer')">Terima</button> <button class="btn btn-danger btn-sm" onclick="reject(${b.id})">Tolak</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Tidak ada bukti yang menunggu verifikasi.</div>'}</div>`}

render();
