<?php
declare(strict_types=1);

$configFile=__DIR__.'/config.php';
if(!file_exists($configFile)){http_response_code(500);header('Content-Type: application/json');echo json_encode(['ok'=>false,'message'=>'Backend belum dikonfigurasi']);exit;}
$config=require $configFile;
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
header('X-Content-Type-Options: nosniff');
header('Referrer-Policy: same-origin');
session_name($config['app']['cookie_name']??'edupay_session');
session_set_cookie_params(['lifetime'=>(int)($config['app']['session_ttl']??43200),'path'=>'/','secure'=>true,'httponly'=>true,'samesite'=>'Lax']);
session_start();

function r53(int $status,array $data):never{http_response_code($status);echo json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function in53():array{$d=json_decode(file_get_contents('php://input')?:'{}',true);return is_array($d)?$d:[];}
function db53(array $c):PDO{return new PDO($c['db']['dsn'],$c['db']['user'],$c['db']['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);}
function school53(PDO $pdo,array $c):int{$code=$c['app']['school_code']??'default-school';$q=$pdo->prepare('SELECT id FROM schools WHERE code=?');$q->execute([$code]);$id=$q->fetchColumn();if(!$id)r53(500,['ok'=>false,'message'=>'Sekolah belum tersedia']);return(int)$id;}
function admin53():array{if(empty($_SESSION['user']))r53(401,['ok'=>false,'message'=>'Belum login']);$u=$_SESSION['user'];if(($u['role']??'')!=='admin')r53(403,['ok'=>false,'message'=>'Akses khusus Administrator']);return$u;}
function csrfToken53():string{if(empty($_SESSION['csrf_v53']))$_SESSION['csrf_v53']=bin2hex(random_bytes(32));return(string)$_SESSION['csrf_v53'];}
function requireCsrf53():void{$got=(string)($_SERVER['HTTP_X_CSRF_TOKEN']??'');$expected=csrfToken53();if($got===''||!hash_equals($expected,$got))r53(419,['ok'=>false,'message'=>'Sesi keamanan kedaluwarsa. Refresh halaman lalu coba lagi.']);}
function audit53(PDO $pdo,int $schoolId,int $userId,string $action,string $entityType,string $entityId,array $meta=[]):void{$q=$pdo->prepare('INSERT INTO audit_logs(school_id,user_id,action,entity_type,entity_id,metadata,ip_address,user_agent) VALUES(?,?,?,?,?,?::jsonb,?,?)');$q->execute([$schoolId,$userId,$action,$entityType,$entityId,json_encode($meta,JSON_UNESCAPED_UNICODE),$_SERVER['REMOTE_ADDR']??null,$_SERVER['HTTP_USER_AGENT']??null]);}
function notifyStudent53(PDO $pdo,int $schoolId,int $studentId,string $type,string $title,string $message,string $entityType,string $entityId):void{$q=$pdo->prepare('SELECT guardian_user_id FROM guardian_students WHERE student_id=?');$q->execute([$studentId]);$ins=$pdo->prepare('INSERT INTO notifications(school_id,user_id,student_id,type,title,message,entity_type,entity_id) VALUES(?,?,?,?,?,?,?,?)');foreach($q->fetchAll() as $g)$ins->execute([$schoolId,(int)$g['guardian_user_id'],$studentId,$type,$title,$message,$entityType,$entityId]);}
function cleanPhone53(string $v):string{$s=preg_replace('/[^0-9+]/','',trim($v));if(str_starts_with($s,'+62'))$s='0'.substr($s,3);elseif(str_starts_with($s,'62'))$s='0'.substr($s,2);return$s;}
function bool53(mixed $v,bool $default=true):bool{return $v===null?$default:(bool)$v;}
function schoolRow53(PDO $pdo,int $schoolId):array{$q=$pdo->prepare('SELECT id,code,name,npsn,address,phone,email,principal_name,treasurer_name,bank_name,bank_account,bank_account_name,qris_info,academic_year_current,semester_current,support_email,app_name,logo_url,active,updated_at FROM schools WHERE id=?');$q->execute([$schoolId]);return$q->fetch()?:[];}
function classRows53(PDO $pdo,int $schoolId):array{$q=$pdo->prepare('SELECT id,name,level,academic_year,active,homeroom_teacher_id FROM classes WHERE school_id=? ORDER BY active DESC,name');$q->execute([$schoolId]);$out=[];foreach($q->fetchAll() as $r)$out[]=['id'=>(int)$r['id'],'name'=>$r['name'],'level'=>$r['level']??'','academicYear'=>$r['academic_year']??'','active'=>(bool)$r['active'],'homeroomTeacherId'=>$r['homeroom_teacher_id']?(int)$r['homeroom_teacher_id']:null];return$out;}
function teacherRows53(PDO $pdo,int $schoolId):array{$q=$pdo->prepare('SELECT id,nip,name,phone,email,active FROM homeroom_teachers WHERE school_id=? ORDER BY active DESC,name');$q->execute([$schoolId]);$out=[];foreach($q->fetchAll() as $r)$out[]=['id'=>(int)$r['id'],'nip'=>$r['nip']??'','name'=>$r['name'],'phone'=>$r['phone']??'','email'=>$r['email']??'','active'=>(bool)$r['active']];return$out;}
function studentRows53(PDO $pdo,int $schoolId):array{$q=$pdo->prepare('SELECT id,nis,name,class_id,guardian_name,guardian_phone,active FROM students WHERE school_id=? ORDER BY active DESC,name');$q->execute([$schoolId]);$out=[];foreach($q->fetchAll() as $r)$out[]=['id'=>(int)$r['id'],'nis'=>$r['nis'],'name'=>$r['name'],'classId'=>$r['class_id']?(int)$r['class_id']:null,'parent'=>$r['guardian_name']??'','phone'=>$r['guardian_phone']??'','active'=>(bool)$r['active']];return$out;}
function feeRows53(PDO $pdo,int $schoolId):array{$q=$pdo->prepare('SELECT id,name,amount,period,active FROM fee_types WHERE school_id=? ORDER BY active DESC,name');$q->execute([$schoolId]);$out=[];foreach($q->fetchAll() as $r)$out[]=['id'=>(int)$r['id'],'name'=>$r['name'],'amount'=>(float)$r['amount'],'period'=>$r['period']??'','active'=>(bool)$r['active']];return$out;}
function billRows53(PDO $pdo,int $schoolId):array{$q=$pdo->prepare("SELECT b.id,b.student_id,b.title,b.amount,b.due_date,b.status,b.payment_method,b.proof_name,s.name student_name,s.guardian_name,s.guardian_phone FROM bills b JOIN students s ON s.id=b.student_id WHERE b.school_id=? ORDER BY b.id DESC");$q->execute([$schoolId]);$out=[];foreach($q->fetchAll() as $r)$out[]=['id'=>(int)$r['id'],'studentId'=>(int)$r['student_id'],'studentName'=>$r['student_name'],'guardianName'=>$r['guardian_name']??'','guardianPhone'=>$r['guardian_phone']??'','title'=>$r['title'],'amount'=>(float)$r['amount'],'due'=>$r['due_date'],'status'=>$r['status'],'paymentMethod'=>$r['payment_method'],'proofName'=>$r['proof_name']];return$out;}
function ensureClass53(PDO $pdo,int $schoolId,int $classId):void{$q=$pdo->prepare('SELECT 1 FROM classes WHERE school_id=? AND id=?');$q->execute([$schoolId,$classId]);if(!$q->fetchColumn())r53(422,['ok'=>false,'message'=>'Kelas tidak valid']);}
function ensureStudent53(PDO $pdo,int $schoolId,int $studentId):void{$q=$pdo->prepare('SELECT 1 FROM students WHERE school_id=? AND id=?');$q->execute([$schoolId,$studentId]);if(!$q->fetchColumn())r53(422,['ok'=>false,'message'=>'Siswa tidak valid']);}

$pdo=db53($config);$schoolId=school53($pdo,$config);$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';$method=$_SERVER['REQUEST_METHOD']??'GET';

if($path==='/api/v53/health'&&$method==='GET')r53(200,['ok'=>true,'version'=>'5.3','commercial_core'=>true,'admin_server_first'=>true,'csrf'=>true]);
if($path==='/api/v53/csrf'&&$method==='GET'){admin53();r53(200,['ok'=>true,'token'=>csrfToken53()]);}
if($path==='/api/v53/admin/state'&&$method==='GET'){admin53();r53(200,['ok'=>true,'school'=>schoolRow53($pdo,$schoolId),'classes'=>classRows53($pdo,$schoolId),'homeroomTeachers'=>teacherRows53($pdo,$schoolId),'students'=>studentRows53($pdo,$schoolId),'feeTypes'=>feeRows53($pdo,$schoolId),'bills'=>billRows53($pdo,$schoolId),'serverTime'=>date(DATE_ATOM)]);}

if($path==='/api/v53/admin/school'&&$method==='POST'){
  $u=admin53();requireCsrf53();$in=in53();$name=trim((string)($in['name']??''));if($name==='')r53(422,['ok'=>false,'message'=>'Nama sekolah wajib diisi']);
  $fields=['npsn','address','phone','email','principalName','treasurerName','bankName','bankAccount','bankAccountName','qrisInfo','academicYear','semester','supportEmail','appName','logoUrl'];
  $vals=[];foreach($fields as $f)$vals[$f]=trim((string)($in[$f]??''));
  if($vals['email']!==''&&!filter_var($vals['email'],FILTER_VALIDATE_EMAIL))r53(422,['ok'=>false,'message'=>'Email sekolah tidak valid']);
  if($vals['supportEmail']!==''&&!filter_var($vals['supportEmail'],FILTER_VALIDATE_EMAIL))r53(422,['ok'=>false,'message'=>'Email support tidak valid']);
  $q=$pdo->prepare('UPDATE schools SET name=?,npsn=?,address=?,phone=?,email=?,principal_name=?,treasurer_name=?,bank_name=?,bank_account=?,bank_account_name=?,qris_info=?,academic_year_current=?,semester_current=?,support_email=?,app_name=?,logo_url=?,updated_at=NOW() WHERE id=?');
  $q->execute([$name,$vals['npsn']?:null,$vals['address']?:null,$vals['phone']?:null,$vals['email']?:null,$vals['principalName']?:null,$vals['treasurerName']?:null,$vals['bankName']?:null,$vals['bankAccount']?:null,$vals['bankAccountName']?:null,$vals['qrisInfo']?:null,$vals['academicYear']?:null,$vals['semester']?:null,$vals['supportEmail']?:null,$vals['appName']?:'EduPay',$vals['logoUrl']?:null,$schoolId]);
  audit53($pdo,$schoolId,(int)$u['id'],'school.updated','school',(string)$schoolId);r53(200,['ok'=>true,'message'=>'Pengaturan sekolah disimpan','school'=>schoolRow53($pdo,$schoolId)]);
}

if($path==='/api/v53/admin/students'&&$method==='POST'){
  $u=admin53();requireCsrf53();$in=in53();$nis=trim((string)($in['nis']??''));$name=trim((string)($in['name']??''));$classId=(int)($in['classId']??0);$parent=trim((string)($in['parent']??''));$phone=cleanPhone53((string)($in['phone']??''));
  if($nis===''||$name===''||$classId<=0||$parent===''||$phone==='')r53(422,['ok'=>false,'message'=>'NIS, nama, kelas, wali dan nomor HP wajib diisi']);ensureClass53($pdo,$schoolId,$classId);
  try{$q=$pdo->prepare('INSERT INTO students(school_id,nis,name,class_id,guardian_name,guardian_phone,active) VALUES(?,?,?,?,?,?,TRUE) RETURNING id');$q->execute([$schoolId,$nis,$name,$classId,$parent,$phone]);$id=(int)$q->fetchColumn();}catch(PDOException $e){if($e->getCode()==='23505')r53(409,['ok'=>false,'message'=>'NIS sudah digunakan']);throw$e;}
  audit53($pdo,$schoolId,(int)$u['id'],'student.created','student',(string)$id,['nis'=>$nis]);r53(201,['ok'=>true,'message'=>'Siswa berhasil ditambahkan','id'=>$id]);
}
if(preg_match('#^/api/v53/admin/students/(\d+)$#',$path,$m)&&$method==='POST'){
  $u=admin53();requireCsrf53();$id=(int)$m[1];$in=in53();$nis=trim((string)($in['nis']??''));$name=trim((string)($in['name']??''));$classId=(int)($in['classId']??0);$parent=trim((string)($in['parent']??''));$phone=cleanPhone53((string)($in['phone']??''));if($nis===''||$name===''||$classId<=0||$parent===''||$phone==='')r53(422,['ok'=>false,'message'=>'Data siswa belum lengkap']);ensureClass53($pdo,$schoolId,$classId);
  try{$q=$pdo->prepare('UPDATE students SET nis=?,name=?,class_id=?,guardian_name=?,guardian_phone=?,updated_at=NOW() WHERE school_id=? AND id=?');$q->execute([$nis,$name,$classId,$parent,$phone,$schoolId,$id]);}catch(PDOException $e){if($e->getCode()==='23505')r53(409,['ok'=>false,'message'=>'NIS sudah digunakan']);throw$e;}if(!$q->rowCount())r53(404,['ok'=>false,'message'=>'Siswa tidak ditemukan']);audit53($pdo,$schoolId,(int)$u['id'],'student.updated','student',(string)$id);r53(200,['ok'=>true,'message'=>'Data siswa berhasil disimpan']);
}
if(preg_match('#^/api/v53/admin/students/(\d+)/status$#',$path,$m)&&$method==='POST'){$u=admin53();requireCsrf53();$id=(int)$m[1];$in=in53();$active=bool53($in['active']??null);$q=$pdo->prepare('UPDATE students SET active=?,updated_at=NOW() WHERE school_id=? AND id=?');$q->execute([$active,$schoolId,$id]);if(!$q->rowCount())r53(404,['ok'=>false,'message'=>'Siswa tidak ditemukan']);audit53($pdo,$schoolId,(int)$u['id'],'student.status','student',(string)$id,['active'=>$active]);r53(200,['ok'=>true,'message'=>$active?'Siswa diaktifkan':'Siswa dinonaktifkan']);}
if($path==='/api/v53/admin/students/import'&&$method==='POST'){
  $u=admin53();requireCsrf53();$in=in53();$rows=is_array($in['students']??null)?$in['students']:[];if(!$rows)r53(422,['ok'=>false,'message'=>'Tidak ada data siswa untuk diimport']);$pdo->beginTransaction();$created=0;$updated=0;
  try{foreach($rows as $s){$nis=trim((string)($s['nis']??''));$name=trim((string)($s['name']??''));$classId=(int)($s['classId']??0);$parent=trim((string)($s['parent']??''));$phone=cleanPhone53((string)($s['phone']??''));if($nis===''||$name===''||$classId<=0||$parent===''||$phone==='')continue;ensureClass53($pdo,$schoolId,$classId);$q=$pdo->prepare('SELECT id FROM students WHERE school_id=? AND nis=?');$q->execute([$schoolId,$nis]);$id=$q->fetchColumn();if($id){$pdo->prepare('UPDATE students SET name=?,class_id=?,guardian_name=?,guardian_phone=?,active=TRUE,updated_at=NOW() WHERE id=?')->execute([$name,$classId,$parent,$phone,$id]);$updated++;}else{$pdo->prepare('INSERT INTO students(school_id,nis,name,class_id,guardian_name,guardian_phone,active) VALUES(?,?,?,?,?,?,TRUE)')->execute([$schoolId,$nis,$name,$classId,$parent,$phone]);$created++;}}$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}audit53($pdo,$schoolId,(int)$u['id'],'student.import','student','bulk',['created'=>$created,'updated'=>$updated]);r53(200,['ok'=>true,'message'=>'Import siswa selesai','created'=>$created,'updated'=>$updated]);
}

if($path==='/api/v53/admin/classes'&&$method==='POST'){
  $u=admin53();requireCsrf53();$in=in53();$name=trim((string)($in['name']??''));$level=trim((string)($in['level']??''));$year=trim((string)($in['academicYear']??''));$teacherId=(int)($in['homeroomTeacherId']??0);if($name===''||$level===''||$year==='')r53(422,['ok'=>false,'message'=>'Nama kelas, tingkat dan tahun ajaran wajib diisi']);if($teacherId>0){$q=$pdo->prepare('SELECT 1 FROM homeroom_teachers WHERE school_id=? AND id=? AND active=TRUE');$q->execute([$schoolId,$teacherId]);if(!$q->fetchColumn())r53(422,['ok'=>false,'message'=>'Wali kelas tidak valid']);$q=$pdo->prepare('SELECT name FROM classes WHERE school_id=? AND homeroom_teacher_id=? AND active=TRUE LIMIT 1');$q->execute([$schoolId,$teacherId]);if($used=$q->fetchColumn())r53(409,['ok'=>false,'message'=>'Wali kelas sudah ditugaskan di '.$used]);}
  try{$q=$pdo->prepare('INSERT INTO classes(school_id,name,level,academic_year,homeroom_teacher_id,active) VALUES(?,?,?,?,?,TRUE) RETURNING id');$q->execute([$schoolId,$name,$level,$year,$teacherId?:null]);$id=(int)$q->fetchColumn();}catch(PDOException $e){if($e->getCode()==='23505')r53(409,['ok'=>false,'message'=>'Kelas sudah ada pada tahun ajaran tersebut']);throw$e;}audit53($pdo,$schoolId,(int)$u['id'],'class.created','class',(string)$id);r53(201,['ok'=>true,'message'=>'Kelas berhasil ditambahkan','id'=>$id]);
}
if(preg_match('#^/api/v53/admin/classes/(\d+)$#',$path,$m)&&$method==='POST'){
  $u=admin53();requireCsrf53();$id=(int)$m[1];$in=in53();$name=trim((string)($in['name']??''));$level=trim((string)($in['level']??''));$year=trim((string)($in['academicYear']??''));$teacherId=(int)($in['homeroomTeacherId']??0);if($name===''||$level===''||$year==='')r53(422,['ok'=>false,'message'=>'Data kelas belum lengkap']);if($teacherId>0){$q=$pdo->prepare('SELECT name FROM classes WHERE school_id=? AND homeroom_teacher_id=? AND active=TRUE AND id<>? LIMIT 1');$q->execute([$schoolId,$teacherId,$id]);if($used=$q->fetchColumn())r53(409,['ok'=>false,'message'=>'Wali kelas sudah ditugaskan di '.$used]);}
  try{$q=$pdo->prepare('UPDATE classes SET name=?,level=?,academic_year=?,homeroom_teacher_id=?,updated_at=NOW() WHERE school_id=? AND id=?');$q->execute([$name,$level,$year,$teacherId?:null,$schoolId,$id]);}catch(PDOException $e){if($e->getCode()==='23505')r53(409,['ok'=>false,'message'=>'Kelas sudah ada pada tahun ajaran tersebut']);throw$e;}if(!$q->rowCount())r53(404,['ok'=>false,'message'=>'Kelas tidak ditemukan']);audit53($pdo,$schoolId,(int)$u['id'],'class.updated','class',(string)$id);r53(200,['ok'=>true,'message'=>'Kelas berhasil disimpan']);
}
if(preg_match('#^/api/v53/admin/classes/(\d+)/status$#',$path,$m)&&$method==='POST'){$u=admin53();requireCsrf53();$id=(int)$m[1];$in=in53();$active=bool53($in['active']??null);if(!$active){$q=$pdo->prepare('SELECT COUNT(*) FROM students WHERE school_id=? AND class_id=? AND active=TRUE');$q->execute([$schoolId,$id]);$count=(int)$q->fetchColumn();if($count>0)r53(409,['ok'=>false,'message'=>'Kelas masih memiliki '.$count.' siswa aktif']);}$q=$pdo->prepare('UPDATE classes SET active=?,updated_at=NOW() WHERE school_id=? AND id=?');$q->execute([$active,$schoolId,$id]);if(!$q->rowCount())r53(404,['ok'=>false,'message'=>'Kelas tidak ditemukan']);audit53($pdo,$schoolId,(int)$u['id'],'class.status','class',(string)$id,['active'=>$active]);r53(200,['ok'=>true,'message'=>$active?'Kelas diaktifkan':'Kelas dinonaktifkan']);}

if($path==='/api/v53/admin/homerooms'&&$method==='POST'){
  $u=admin53();requireCsrf53();$in=in53();$nip=trim((string)($in['nip']??''));$name=trim((string)($in['name']??''));$phone=cleanPhone53((string)($in['phone']??''));$email=trim((string)($in['email']??''));if($name==='')r53(422,['ok'=>false,'message'=>'Nama wali kelas wajib diisi']);if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))r53(422,['ok'=>false,'message'=>'Email tidak valid']);try{$q=$pdo->prepare('INSERT INTO homeroom_teachers(school_id,nip,name,phone,email,active) VALUES(?,?,?,?,?,TRUE) RETURNING id');$q->execute([$schoolId,$nip?:null,$name,$phone?:null,$email?:null]);$id=(int)$q->fetchColumn();}catch(PDOException $e){if($e->getCode()==='23505')r53(409,['ok'=>false,'message'=>'NIP/NIK sudah digunakan']);throw$e;}audit53($pdo,$schoolId,(int)$u['id'],'homeroom.created','homeroom_teacher',(string)$id);r53(201,['ok'=>true,'message'=>'Wali kelas berhasil ditambahkan','id'=>$id]);
}
if(preg_match('#^/api/v53/admin/homerooms/(\d+)$#',$path,$m)&&$method==='POST'){$u=admin53();requireCsrf53();$id=(int)$m[1];$in=in53();$nip=trim((string)($in['nip']??''));$name=trim((string)($in['name']??''));$phone=cleanPhone53((string)($in['phone']??''));$email=trim((string)($in['email']??''));if($name==='')r53(422,['ok'=>false,'message'=>'Nama wali kelas wajib diisi']);if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))r53(422,['ok'=>false,'message'=>'Email tidak valid']);try{$q=$pdo->prepare('UPDATE homeroom_teachers SET nip=?,name=?,phone=?,email=?,updated_at=NOW() WHERE school_id=? AND id=?');$q->execute([$nip?:null,$name,$phone?:null,$email?:null,$schoolId,$id]);}catch(PDOException $e){if($e->getCode()==='23505')r53(409,['ok'=>false,'message'=>'NIP/NIK sudah digunakan']);throw$e;}if(!$q->rowCount())r53(404,['ok'=>false,'message'=>'Wali kelas tidak ditemukan']);audit53($pdo,$schoolId,(int)$u['id'],'homeroom.updated','homeroom_teacher',(string)$id);r53(200,['ok'=>true,'message'=>'Wali kelas berhasil disimpan']);}
if(preg_match('#^/api/v53/admin/homerooms/(\d+)/status$#',$path,$m)&&$method==='POST'){$u=admin53();requireCsrf53();$id=(int)$m[1];$in=in53();$active=bool53($in['active']??null);if(!$active){$q=$pdo->prepare('SELECT name FROM classes WHERE school_id=? AND homeroom_teacher_id=? AND active=TRUE LIMIT 1');$q->execute([$schoolId,$id]);if($cls=$q->fetchColumn())r53(409,['ok'=>false,'message'=>'Masih menjadi wali kelas '.$cls]);}$q=$pdo->prepare('UPDATE homeroom_teachers SET active=?,updated_at=NOW() WHERE school_id=? AND id=?');$q->execute([$active,$schoolId,$id]);if(!$q->rowCount())r53(404,['ok'=>false,'message'=>'Wali kelas tidak ditemukan']);audit53($pdo,$schoolId,(int)$u['id'],'homeroom.status','homeroom_teacher',(string)$id,['active'=>$active]);r53(200,['ok'=>true,'message'=>$active?'Wali kelas diaktifkan':'Wali kelas dinonaktifkan']);}
if($path==='/api/v53/admin/homerooms/import'&&$method==='POST'){
  $u=admin53();requireCsrf53();$in=in53();$rows=is_array($in['teachers']??null)?$in['teachers']:[];if(!$rows)r53(422,['ok'=>false,'message'=>'Tidak ada data wali kelas untuk diimport']);$pdo->beginTransaction();$created=0;$updated=0;
  try{foreach($rows as $t){$nip=trim((string)($t['nip']??''));$name=trim((string)($t['name']??''));$phone=cleanPhone53((string)($t['phone']??''));$email=trim((string)($t['email']??''));$classId=(int)($t['classId']??0);if($name==='')continue;if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))continue;$id=null;if($nip!==''){$q=$pdo->prepare('SELECT id FROM homeroom_teachers WHERE school_id=? AND nip=?');$q->execute([$schoolId,$nip]);$id=$q->fetchColumn();}if($id){$pdo->prepare('UPDATE homeroom_teachers SET name=?,phone=?,email=?,active=TRUE,updated_at=NOW() WHERE id=?')->execute([$name,$phone?:null,$email?:null,$id]);$updated++;}else{$q=$pdo->prepare('INSERT INTO homeroom_teachers(school_id,nip,name,phone,email,active) VALUES(?,?,?,?,?,TRUE) RETURNING id');$q->execute([$schoolId,$nip?:null,$name,$phone?:null,$email?:null]);$id=$q->fetchColumn();$created++;}if($classId>0){ensureClass53($pdo,$schoolId,$classId);$q=$pdo->prepare('SELECT name FROM classes WHERE school_id=? AND homeroom_teacher_id=? AND active=TRUE AND id<>? LIMIT 1');$q->execute([$schoolId,$id,$classId]);if($q->fetchColumn())continue;$pdo->prepare('UPDATE classes SET homeroom_teacher_id=NULL,updated_at=NOW() WHERE school_id=? AND homeroom_teacher_id=? AND id<>?')->execute([$schoolId,$id,$classId]);$pdo->prepare('UPDATE classes SET homeroom_teacher_id=?,updated_at=NOW() WHERE school_id=? AND id=?')->execute([$id,$schoolId,$classId]);}}$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}audit53($pdo,$schoolId,(int)$u['id'],'homeroom.import','homeroom_teacher','bulk',['created'=>$created,'updated'=>$updated]);r53(200,['ok'=>true,'message'=>'Import wali kelas selesai','created'=>$created,'updated'=>$updated]);
}

if($path==='/api/v53/admin/fee-types'&&$method==='POST'){$u=admin53();requireCsrf53();$in=in53();$name=trim((string)($in['name']??''));$amount=(float)($in['amount']??0);$period=trim((string)($in['period']??''));if($name===''||$amount<0)r53(422,['ok'=>false,'message'=>'Jenis pembayaran tidak valid']);try{$q=$pdo->prepare('INSERT INTO fee_types(school_id,name,amount,period,active) VALUES(?,?,?,?,TRUE) RETURNING id');$q->execute([$schoolId,$name,$amount,$period?:null]);$id=(int)$q->fetchColumn();}catch(PDOException $e){if($e->getCode()==='23505')r53(409,['ok'=>false,'message'=>'Jenis pembayaran sudah ada']);throw$e;}audit53($pdo,$schoolId,(int)$u['id'],'fee.created','fee_type',(string)$id);r53(201,['ok'=>true,'message'=>'Jenis pembayaran ditambahkan','id'=>$id]);}
if(preg_match('#^/api/v53/admin/fee-types/(\d+)$#',$path,$m)&&$method==='POST'){$u=admin53();requireCsrf53();$id=(int)$m[1];$in=in53();$name=trim((string)($in['name']??''));$amount=(float)($in['amount']??0);$period=trim((string)($in['period']??''));if($name===''||$amount<0)r53(422,['ok'=>false,'message'=>'Jenis pembayaran tidak valid']);try{$q=$pdo->prepare('UPDATE fee_types SET name=?,amount=?,period=?,updated_at=NOW() WHERE school_id=? AND id=?');$q->execute([$name,$amount,$period?:null,$schoolId,$id]);}catch(PDOException $e){if($e->getCode()==='23505')r53(409,['ok'=>false,'message'=>'Jenis pembayaran sudah ada']);throw$e;}if(!$q->rowCount())r53(404,['ok'=>false,'message'=>'Jenis pembayaran tidak ditemukan']);audit53($pdo,$schoolId,(int)$u['id'],'fee.updated','fee_type',(string)$id);r53(200,['ok'=>true,'message'=>'Jenis pembayaran disimpan']);}
if(preg_match('#^/api/v53/admin/fee-types/(\d+)/status$#',$path,$m)&&$method==='POST'){$u=admin53();requireCsrf53();$id=(int)$m[1];$in=in53();$active=bool53($in['active']??null);$q=$pdo->prepare('UPDATE fee_types SET active=?,updated_at=NOW() WHERE school_id=? AND id=?');$q->execute([$active,$schoolId,$id]);if(!$q->rowCount())r53(404,['ok'=>false,'message'=>'Jenis pembayaran tidak ditemukan']);audit53($pdo,$schoolId,(int)$u['id'],'fee.status','fee_type',(string)$id,['active'=>$active]);r53(200,['ok'=>true,'message'=>$active?'Jenis pembayaran diaktifkan':'Jenis pembayaran dinonaktifkan']);}

if($path==='/api/v53/admin/bills'&&$method==='POST'){
  $u=admin53();requireCsrf53();$in=in53();$studentId=(int)($in['studentId']??0);$title=trim((string)($in['title']??''));$amount=(float)($in['amount']??0);$due=trim((string)($in['due']??''));if($studentId<=0||$title===''||$amount<0||$due==='')r53(422,['ok'=>false,'message'=>'Data tagihan belum lengkap']);ensureStudent53($pdo,$schoolId,$studentId);$q=$pdo->prepare("SELECT id FROM bills WHERE school_id=? AND student_id=? AND title=? AND due_date=? AND status<>'cancelled' LIMIT 1");$q->execute([$schoolId,$studentId,$title,$due]);if($q->fetchColumn())r53(409,['ok'=>false,'message'=>'Tagihan yang sama sudah ada untuk siswa ini']);$q=$pdo->prepare("INSERT INTO bills(school_id,student_id,title,amount,due_date,status) VALUES(?,?,?,?,?,'unpaid') RETURNING id");$q->execute([$schoolId,$studentId,$title,$amount,$due]);$id=(int)$q->fetchColumn();audit53($pdo,$schoolId,(int)$u['id'],'bill.created','bill',(string)$id,['amount'=>$amount]);notifyStudent53($pdo,$schoolId,$studentId,'bill','Tagihan baru','Tagihan '.$title.' sebesar Rp '.number_format($amount,0,',','.').' telah diterbitkan.','bill',(string)$id);r53(201,['ok'=>true,'message'=>'Tagihan berhasil dibuat','id'=>$id]);
}
if(preg_match('#^/api/v53/admin/bills/(\d+)$#',$path,$m)&&$method==='POST'){$u=admin53();requireCsrf53();$id=(int)$m[1];$in=in53();$studentId=(int)($in['studentId']??0);$title=trim((string)($in['title']??''));$amount=(float)($in['amount']??0);$due=trim((string)($in['due']??''));$q=$pdo->prepare('SELECT status FROM bills WHERE school_id=? AND id=?');$q->execute([$schoolId,$id]);$status=$q->fetchColumn();if(!$status)r53(404,['ok'=>false,'message'=>'Tagihan tidak ditemukan']);if($status==='paid')r53(409,['ok'=>false,'message'=>'Tagihan lunas tidak dapat diubah']);if($studentId<=0||$title===''||$amount<0||$due==='')r53(422,['ok'=>false,'message'=>'Data tagihan belum lengkap']);ensureStudent53($pdo,$schoolId,$studentId);$q=$pdo->prepare('UPDATE bills SET student_id=?,title=?,amount=?,due_date=?,updated_at=NOW() WHERE school_id=? AND id=?');$q->execute([$studentId,$title,$amount,$due,$schoolId,$id]);audit53($pdo,$schoolId,(int)$u['id'],'bill.updated','bill',(string)$id);r53(200,['ok'=>true,'message'=>'Tagihan berhasil disimpan']);}
if(preg_match('#^/api/v53/admin/bills/(\d+)/cancel$#',$path,$m)&&$method==='POST'){$u=admin53();requireCsrf53();$id=(int)$m[1];$q=$pdo->prepare("UPDATE bills SET status='cancelled',updated_at=NOW() WHERE school_id=? AND id=? AND status<>'paid'");$q->execute([$schoolId,$id]);if(!$q->rowCount())r53(409,['ok'=>false,'message'=>'Tagihan tidak dapat dibatalkan']);audit53($pdo,$schoolId,(int)$u['id'],'bill.cancelled','bill',(string)$id);r53(200,['ok'=>true,'message'=>'Tagihan dibatalkan']);}
if(preg_match('#^/api/v53/admin/bills/(\d+)/restore$#',$path,$m)&&$method==='POST'){$u=admin53();requireCsrf53();$id=(int)$m[1];$q=$pdo->prepare("UPDATE bills SET status='unpaid',updated_at=NOW() WHERE school_id=? AND id=? AND status='cancelled'");$q->execute([$schoolId,$id]);if(!$q->rowCount())r53(409,['ok'=>false,'message'=>'Tagihan tidak dapat dipulihkan']);audit53($pdo,$schoolId,(int)$u['id'],'bill.restored','bill',(string)$id);r53(200,['ok'=>true,'message'=>'Tagihan dipulihkan']);}
if($path==='/api/v53/admin/bills/mass'&&$method==='POST'){
  $u=admin53();requireCsrf53();$in=in53();$classId=(string)($in['classId']??'all');$title=trim((string)($in['title']??''));$amount=(float)($in['amount']??0);$due=trim((string)($in['due']??''));if($title===''||$amount<0||$due==='')r53(422,['ok'=>false,'message'=>'Data tagihan massal belum lengkap']);$sql='SELECT id FROM students WHERE school_id=? AND active=TRUE';$args=[$schoolId];if($classId!=='all'){$cid=(int)$classId;ensureClass53($pdo,$schoolId,$cid);$sql.=' AND class_id=?';$args[]=$cid;}$q=$pdo->prepare($sql);$q->execute($args);$students=array_map('intval',array_column($q->fetchAll(),'id'));$created=0;$skipped=0;$pdo->beginTransaction();
  try{foreach($students as $sid){$q=$pdo->prepare("SELECT 1 FROM bills WHERE school_id=? AND student_id=? AND title=? AND due_date=? AND status<>'cancelled' LIMIT 1");$q->execute([$schoolId,$sid,$title,$due]);if($q->fetchColumn()){$skipped++;continue;}$q=$pdo->prepare("INSERT INTO bills(school_id,student_id,title,amount,due_date,status) VALUES(?,?,?,?,?,'unpaid') RETURNING id");$q->execute([$schoolId,$sid,$title,$amount,$due]);$bid=(int)$q->fetchColumn();notifyStudent53($pdo,$schoolId,$sid,'bill','Tagihan baru','Tagihan '.$title.' sebesar Rp '.number_format($amount,0,',','.').' telah diterbitkan.','bill',(string)$bid);$created++;}$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}audit53($pdo,$schoolId,(int)$u['id'],'bill.mass_created','bill','bulk',['created'=>$created,'skipped'=>$skipped,'title'=>$title]);r53(200,['ok'=>true,'message'=>$created.' tagihan berhasil dibuat','created'=>$created,'skipped'=>$skipped]);
}

r53(404,['ok'=>false,'message'=>'Endpoint V5.3 tidak ditemukan']);
