<?php
declare(strict_types=1);
$configFile=__DIR__.'/config.php';if(!file_exists($configFile)){http_response_code(500);exit;}$config=require$configFile;
header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');session_name($config['app']['cookie_name']??'edupay_session');session_set_cookie_params(['lifetime'=>(int)($config['app']['session_ttl']??43200),'path'=>'/','secure'=>true,'httponly'=>true,'samesite'=>'Lax']);if(session_status()!==PHP_SESSION_ACTIVE)session_start();
function r56f(int$s,array$d):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function in56f():array{$d=json_decode(file_get_contents('php://input')?:'{}',true);return is_array($d)?$d:[];}
function db56f(array$c):PDO{return new PDO($c['db']['dsn'],$c['db']['user'],$c['db']['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);}
function school56f(PDO$p,array$c):int{$q=$p->prepare('SELECT id FROM schools WHERE code=?');$q->execute([$c['app']['school_code']??'default-school']);$id=$q->fetchColumn();if(!$id)r56f(500,['ok'=>false,'message'=>'Sekolah tidak ditemukan']);return(int)$id;}
function actor56f(array$roles):array{if(empty($_SESSION['user']))r56f(401,['ok'=>false,'message'=>'Belum login']);$u=$_SESSION['user'];if(!in_array($u['role']??'',$roles,true))r56f(403,['ok'=>false,'message'=>'Akses ditolak']);return$u;}
function audit56f(PDO$p,int$s,int$u,string$a,string$t,string$id,array$m=[]):void{$q=$p->prepare('INSERT INTO audit_logs(school_id,user_id,action,entity_type,entity_id,metadata,ip_address,user_agent) VALUES(?,?,?,?,?,?::jsonb,?,?)');$q->execute([$s,$u,$a,$t,$id,json_encode($m,JSON_UNESCAPED_UNICODE),$_SERVER['REMOTE_ADDR']??null,$_SERVER['HTTP_USER_AGENT']??null]);}
function notify56f(PDO$p,int$s,int$student,string$title,string$message,string$eid):void{$q=$p->prepare('SELECT guardian_user_id FROM guardian_students WHERE student_id=?');$q->execute([$student]);$i=$p->prepare("INSERT INTO notifications(school_id,user_id,student_id,type,title,message,entity_type,entity_id) VALUES(?,?,?,'payment',?,?, 'payment',?)");foreach($q->fetchAll()as$g)$i->execute([$s,(int)$g['guardian_user_id'],$student,$title,$message,$eid]);}
function nextReceipt56f(PDO$p,int$s):string{$q=$p->prepare("SELECT COALESCE(NULLIF(receipt_prefix,''),'PAY') prefix FROM schools WHERE id=?");$q->execute([$s]);$prefix=strtoupper((string)($q->fetchColumn()?:'PAY'));$prefix=preg_replace('/[^A-Z0-9-]/','',$prefix)?:'PAY';$q=$p->prepare("INSERT INTO receipt_counters(school_id,counter_date,last_number) VALUES(?,CURRENT_DATE,1) ON CONFLICT(school_id,counter_date) DO UPDATE SET last_number=receipt_counters.last_number+1,updated_at=NOW() RETURNING counter_date,last_number");$q->execute([$s]);$r=$q->fetch();return$prefix.'-'.date('Ymd',strtotime((string)$r['counter_date'])).'-'.str_pad((string)$r['last_number'],5,'0',STR_PAD_LEFT);}
function lockBill56f(PDO$p,int$s,int$id):array{$q=$p->prepare('SELECT b.*,s.name student_name FROM bills b JOIN students s ON s.id=b.student_id WHERE b.school_id=? AND b.id=? FOR UPDATE OF b');$q->execute([$s,$id]);$b=$q->fetch();if(!$b)r56f(404,['ok'=>false,'message'=>'Tagihan tidak ditemukan']);return$b;}
function createPayment56f(PDO$p,int$s,array$u,array$b,string$method,bool$proofRequired=false):array{if($b['status']==='cancelled')r56f(409,['ok'=>false,'message'=>'Tagihan dibatalkan']);$q=$p->prepare('SELECT 1 FROM payments WHERE bill_id=? AND voided=FALSE LIMIT 1');$q->execute([$b['id']]);if($b['status']==='paid'||$q->fetchColumn())r56f(409,['ok'=>false,'message'=>'Tagihan sudah diproses']);if($proofRequired&&trim((string)($b['proof_storage_key']??''))==='')r56f(409,['ok'=>false,'message'=>'Bukti transfer belum tersimpan sebagai file di VPS']);$receipt=nextReceipt56f($p,$s);$q=$p->prepare('INSERT INTO payments(school_id,external_id,bill_id,student_id,amount,method,paid_at,verified_by,receipt,voided) VALUES(?,?,?,?,?,?,NOW(),?,?,FALSE) RETURNING id,paid_at');$q->execute([$s,'server:'.$receipt,$b['id'],$b['student_id'],$b['amount'],$method,$u['id'],$receipt]);$pay=$q->fetch();$p->prepare("UPDATE bills SET status='paid',payment_method=?,updated_at=NOW() WHERE id=?")->execute([$method,$b['id']]);audit56f($p,$s,(int)$u['id'],'payment.created','payment',(string)$pay['id'],['bill_id'=>(int)$b['id'],'receipt'=>$receipt,'method'=>$method,'amount'=>(float)$b['amount'],'v'=>'5.6']);notify56f($p,$s,(int)$b['student_id'],'Pembayaran dikonfirmasi','Pembayaran '.$b['title'].' telah dinyatakan lunas. Kwitansi: '.$receipt,(string)$pay['id']);return['id'=>(int)$pay['id'],'receipt'=>$receipt,'paid_at'=>$pay['paid_at'],'amount'=>(float)$b['amount'],'method'=>$method];}

$pdo=db56f($config);$school=school56f($pdo,$config);$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';$method=$_SERVER['REQUEST_METHOD']??'GET';
if(preg_match('#^/api/v56finance/finance/bills/(\d+)/pay$#',$path,$m)&&$method==='POST'){$u=actor56f(['finance']);$in=in56f();$pm=trim((string)($in['method']??'Cash'));if(!in_array($pm,['Cash','Transfer','QRIS'],true))r56f(422,['ok'=>false,'message'=>'Metode tidak valid']);$pdo->beginTransaction();try{$b=lockBill56f($pdo,$school,(int)$m[1]);if($b['status']==='pending'&&$pm!=='Transfer')r56f(409,['ok'=>false,'message'=>'Tagihan menunggu verifikasi transfer. Terima atau Tolak bukti terlebih dahulu.']);$p=createPayment56f($pdo,$school,$u,$b,$pm,$b['status']==='pending');$pdo->commit();r56f(200,['ok'=>true,'message'=>'Pembayaran berhasil dicatat','payment'=>$p]);}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
if(preg_match('#^/api/v56finance/finance/bills/(\d+)/approve$#',$path,$m)&&$method==='POST'){$u=actor56f(['finance']);$pdo->beginTransaction();try{$b=lockBill56f($pdo,$school,(int)$m[1]);if($b['status']!=='pending')r56f(409,['ok'=>false,'message'=>'Tagihan tidak menunggu verifikasi']);$p=createPayment56f($pdo,$school,$u,$b,'Transfer',true);$pdo->commit();r56f(200,['ok'=>true,'message'=>'Bukti diterima dan pembayaran dilunaskan','payment'=>$p]);}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
if(preg_match('#^/api/v56finance/verification/bills/(\d+)/approve$#',$path,$m)&&$method==='POST'){$u=actor56f(['admin','finance']);$pdo->beginTransaction();try{$b=lockBill56f($pdo,$school,(int)$m[1]);if($b['status']!=='pending')r56f(409,['ok'=>false,'message'=>'Tagihan tidak menunggu verifikasi']);$p=createPayment56f($pdo,$school,$u,$b,'Transfer',true);$pdo->commit();r56f(200,['ok'=>true,'message'=>'Bukti diterima dan pembayaran dinyatakan lunas','receipt'=>$p['receipt'],'payment'=>$p]);}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}}
r56f(404,['ok'=>false,'message'=>'Endpoint transaksi V5.6 tidak ditemukan']);
