<?php
declare(strict_types=1);
$configFile=__DIR__.'/config.php';if(!file_exists($configFile)){http_response_code(500);exit;}$config=require$configFile;header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');session_name($config['app']['cookie_name']??'edupay_session');session_set_cookie_params(['lifetime'=>(int)($config['app']['session_ttl']??43200),'path'=>'/','secure'=>true,'httponly'=>true,'samesite'=>'Lax']);if(session_status()!==PHP_SESSION_ACTIVE)session_start();
function r56s(int$s,array$d):never{http_response_code($s);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
if(empty($_SESSION['user'])||!in_array($_SESSION['user']['role']??'',['admin','finance'],true))r56s(401,['ok'=>false,'message'=>'Belum login']);
$pdo=new PDO($config['db']['dsn'],$config['db']['user'],$config['db']['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$q=$pdo->prepare('SELECT id FROM schools WHERE code=?');$q->execute([$config['app']['school_code']??'default-school']);$school=(int)$q->fetchColumn();if(!$school)r56s(500,['ok'=>false,'message'=>'Sekolah tidak ditemukan']);$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';if($path!=='/api/v56scale/dashboard')r56s(404,['ok'=>false,'message'=>'Endpoint tidak ditemukan']);
$q=$pdo->prepare("SELECT COALESCE(SUM(CASE WHEN status<>'cancelled' THEN amount ELSE 0 END),0) total_billed,COALESCE(SUM(CASE WHEN status='paid' THEN amount ELSE 0 END),0) paid_amount,COALESCE(SUM(CASE WHEN status='unpaid' THEN amount ELSE 0 END),0) unpaid_amount,COALESCE(SUM(CASE WHEN status='pending' THEN amount ELSE 0 END),0) pending_amount,COALESCE(SUM(CASE WHEN status='pending' THEN 1 ELSE 0 END),0) pending_count,COALESCE(SUM(CASE WHEN status='unpaid' AND due_date<CURRENT_DATE THEN 1 ELSE 0 END),0) overdue_count FROM bills WHERE school_id=?");$q->execute([$school]);$b=$q->fetch()?:[];
$q=$pdo->prepare("SELECT COALESCE(SUM(CASE WHEN COALESCE(voided,FALSE)=FALSE AND paid_at::date=CURRENT_DATE THEN amount ELSE 0 END),0) today_amount,COALESCE(SUM(CASE WHEN COALESCE(voided,FALSE)=FALSE AND date_trunc('month',paid_at)=date_trunc('month',CURRENT_TIMESTAMP) THEN amount ELSE 0 END),0) month_amount FROM payments WHERE school_id=?");$q->execute([$school]);$p=$q->fetch()?:[];
$q=$pdo->prepare("SELECT (SELECT COUNT(*) FROM students WHERE school_id=? AND active=TRUE) active_students,(SELECT COUNT(*) FROM users WHERE school_id=? AND role='parent' AND status='active') active_guardians");$q->execute([$school,$school]);$people=$q->fetch()?:[];
$q=$pdo->prepare('SELECT p.id,p.receipt,p.amount,p.method,p.paid_at,COALESCE(p.voided,FALSE) voided,s.name student_name,b.title FROM payments p JOIN students s ON s.id=p.student_id JOIN bills b ON b.id=p.bill_id WHERE p.school_id=? ORDER BY p.paid_at DESC,p.id DESC LIMIT 5');$q->execute([$school]);$latest=[];foreach($q->fetchAll()as$x)$latest[]=['id'=>(int)$x['id'],'receipt'=>$x['receipt'],'amount'=>(float)$x['amount'],'method'=>$x['method'],'paidAt'=>$x['paid_at'],'voided'=>(bool)$x['voided'],'studentName'=>$x['student_name'],'title'=>$x['title']];
r56s(200,['ok'=>true,'summary'=>['totalBilled'=>(float)($b['total_billed']??0),'paid'=>(float)($b['paid_amount']??0),'unpaid'=>(float)($b['unpaid_amount']??0),'pendingAmount'=>(float)($b['pending_amount']??0),'pendingCount'=>(int)($b['pending_count']??0),'overdueCount'=>(int)($b['overdue_count']??0),'today'=>(float)($p['today_amount']??0),'month'=>(float)($p['month_amount']??0),'activeStudents'=>(int)($people['active_students']??0),'activeGuardians'=>(int)($people['active_guardians']??0)],'latestPayments'=>$latest,'serverTime'=>date(DATE_ATOM)]);
